ori:
  time: 0
  month: 1
  from: 2
  inOrex: 3
  counterparty: 7
  goods: 8
  money: 9
  class: 10
  tag: 11

wx:
  header: 16
  footer: 0
  time: 0
  inOrex: 4
  payWay: 6
  state: 7
  type: 1
  counterparty: 2
  goods: 3
  amount: 5

zfb:
  header: 22
  footer: 0
  time: 0
  inOrex: 5
  payWay: 7
  state: 8
  type: 1
  counterparty: 2
  goods: 4
  amount: 6

filePath:
  root_dir: files
  invalid: resources/invalid.txt
  processed_file: resources/processed_files.txt
  path_write: resources/2024年记账.xlsx
  invalid_file: resources/无用数据.xlsx
  tag: resources/tag.xlsx
